@grammar TinyXML

XML = ~ws? element ~ws?
element = void_element | non_void_element

non_void_element = start_tag content end_tag
void_element = ~"<" name attr_list ~"/>"
start_tag = ~"<" name attr_list ~">"
end_tag = ~"</" name ~">"

content = (pcdata | element)*
@inline pcdata = /[^<]+/

attr_list = (~ws attr)*
attr = name ~"=" attr_value
@inline attr_value = /" [^<"]* "/ | /' [^<']* '/

@inline name = /[\w-]+/
@inline ws = /\s+/
