
##################### terminals 
WS          = /\s+/
EQUALS      = '='
BANG        = '!'
AMP         = '&'
LPAREN      = '('
RPAREN      = ')'
PIPE        = '|'
COMMENT     = / #([^\r\n]*) /
IDENTIFIER  = / [a-zA-Z_]\w* /
STRING      = / (["\']) ((?: (?:\\.) | (?:(?!\1).) )*) \1 /
QUANTIFIER  = / ([*+?]) | (?: \{ (\d+)(?:,(\d*))? \} ) /
REGEX       = / \/ ((?: (?:\\.) | [^\/] )*) \/ ([ilmsux]*)? /

##################### rules
ws_com      = WS | COMMENT
_           = ws_com*
directive   = PERCENT IDENTIFIER
label       = IDENTIFIER ':'
reference   = IDENTIFIER _ !equals
literal     = STRING _
regex       = REGEX _
quantifier  = QUANTIFIER _
paren_expr  = LPAREN _ expression _ RPAREN _
atom        = reference | literal | regex | paren_expr
quantified  = atom quantifier
lookahead   = AMP term _
not         = BANG term _
labeld      = label term _
term        = not | lookahead | quantified | atom


rule        = IDENTIFIER _ EQUALS _ expression
