<?php declare(strict_types=1);
/*
 * This file is part of Pegasus
 *
 * © 2014 Jules Bernable
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace ju1ius\Pegasus\Expression\Terminal;

use ju1ius\Pegasus\CST\Node;
use ju1ius\Pegasus\Expression\Terminal;
use ju1ius\Pegasus\Parser\Parser;

/**
 * This type of expression is generated by the optimizer,
 * as the result of combining multiple consecutive Match expressions
 * into one optimized regular expression.
 *
 * You should not use it directly.
 *
 * @internal
 *
 * @author ju1ius <ju1ius@laposte.net>
 */
final class GroupMatch extends Terminal
{
    /**
     * @var Match
     */
    private $matcher;

    /**
     * @var int
     */
    private $groupCount;

    /**
     * @var string
     */
    private $compiledPattern;

    /**
     * GroupMatch constructor.
     *
     * @param Match  $match
     * @param int    $groupCount
     * @param string $name
     */
    public function __construct(Match $match, int $groupCount, string $name = '')
    {
        $this->matcher = $match;
        $this->groupCount = $groupCount;
        $this->compiledPattern = $match->getCompiledPattern();

        parent::__construct($name);
    }

    public function getMatcher(): Match
    {
        return $this->matcher;
    }

    public function getPattern(): string
    {
        return $this->matcher->getPattern();
    }

    /**
     * @return string[]
     */
    public function getFlags(): array
    {
        return $this->matcher->getFlags();
    }

    public function getCompiledPattern(): string
    {
        return $this->compiledPattern;
    }

    public function getCaptureCount(): int
    {
        return $this->groupCount;
    }

    /**
     * @inheritDoc
     */
    public function match(string $text, Parser $parser)
    {
        $start = $parser->pos;
        if (preg_match($this->compiledPattern, $text, $matches, 0, $start)) {
            $end = $parser->pos += strlen($matches[0]);
            if (!$parser->isCapturing) {
                return true;
            }

            if ($this->groupCount === 1) {
                return new Node\Terminal($this->name, $start, $end, $matches[1]);
            }

            return new Node\Terminal($this->name, $start, $end, $matches[0], [
                'captures' => array_slice($matches, 1)
            ]);
        }
        return false;
    }

    /**
     * @inheritDoc
     */
    public function __toString(): string
    {
        return sprintf('GroupMatch[%s, %d]', $this->compiledPattern, $this->groupCount);
    }
}
